### ISSUE TITLE
Playground broken in Firefox (88.0 stable and 89.0b2 beta)

### ISSUE THREAD

**Issue by robertkruis** [ryansolid/solid-playground#11]
The playground stopped working for me in Firefox (both stable and beta). Earlier today I've been prototyping on the playground without any issues, but as of tonight the playground seems broken. Chromium based browsers still seem to be working correctly. This happens immediately to the default sample of the playground.

To reproduce, simply open the playground in the stable or beta release of Firefox and open the devtools console. Errors will be logged and no content is show in the result pane of the playground. 

Please find attached the devtools console output:
[console-export-2021-4-21_21-5-23.txt](https://github.com/ryansolid/solid-playground/files/6353377/console-export-2021-4-21_21-5-23.txt)

**Comment by amoutonbrady** [comment]
Yeah I've accidentally updated Vite to latest which broke a patch we had in place. This was fixed this morning thanks to @modderme123 PR #12 .

Let me know if things are still broken.
